#   ____         __    ___                              
#  / __/__ ____ / /_  / _ \___ ___ ___  ___ __    _____ 
# / _// _ `(_-</ __/ / , _/ -_|_-</ _ \/ _ `/ |/|/ / _ \
#/_/  \_,_/___/\__/ /_/|_|\__/___/ .__/\_,_/|__,__/_//_/
#                               /_/                           


Options:
  Title: false
  Sound: false
  
  
Fast-Respawn:
  Sound: "DONKEY_DEATH"
  Line1: "&c&LFAILED"
  Line2: ""
